services:
    backend-app:
        command: "java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5600 -jar backend.jar"
        container_name: movement-backend-application
        build:
            context: ./backend
            dockerfile: Dockerfile
        depends_on:
            - db
        env_file:
            - .env
        environment:
            ENV: docker
            DATABASE_URL: ${DATABASE_URL}
        networks:
            - movement-network
        ports:
            - "6000:6000"
            - "5600:5600"
    db:
        container_name: movement-database
        env_file:
            - .env
        environment:
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
            POSTGRES_USER: ${DATABASE_USERNAME}
            POSTGRES_MULTIPLE_DATABASES: ${POSTGRES_MULTIPLE_DATABASES}
        hostname: personal-finance-db
        image: postgres:14.3-alpine
        networks:
            - movement-network
        ports:
            - "5432:5432"
        restart: always
        volumes:
            - ./postgres/postgres-multiple-databases.sh:/docker-entrypoint-initdb.d/postgres-multiple-databases.sh
            - dataBaseApplication:/var/lib/postgresql/data
    frontend-app:
        build:
            context: ./frontend
            dockerfile: ./Dockerfile
        command: yarn start
        container_name: movement-frontend-application
        depends_on:
            - backend-app
        ports:
            - "8000:8000"
        volumes:
            - ./frontend/:/usr/src/app
            - ./frontend/public/assets:/usr/src/app/public/assets
        stdin_open: true
        tty: true
        env_file:
            - .env
        networks:
            - movement-network
networks:
    movement-network:
volumes:
    dataBaseApplication:
