CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS PRODUTO(
    COD_PRODUTO UUID NOT NULL DEFAULT uuid_generate_v4(),
    STA_STATUS BOOLEAN NOT NULL DEFAULT TRUE,
    DES_PRODUTO VARCHAR(150) UNIQUE NOT NULL CHECK (DES_PRODUTO <> ''),
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_PRODUTO_ID PRIMARY KEY(COD_PRODUTO)
);