CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS PRODUTO_COSIF(
    COD_PRODUTO UUID NOT NULL,
    COD_COSIF UUID NOT NULL DEFAULT uuid_generate_v4(),
    COD_CLASSIFICACAO VARCHAR(150) NOT NULL CHECK (COD_CLASSIFICACAO <> ''),
    STA_STATUS BOOLEAN NOT NULL DEFAULT TRUE,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_PRODUTO_COSIF_COD_PRODUTO_AND_COD_COSIF PRIMARY KEY(COD_PRODUTO, COD_COSIF),
    CONSTRAINT FK_PRODUTO_COD_PRODUTO FOREIGN KEY(COD_PRODUTO) REFERENCES PRODUTO(COD_PRODUTO)
);

CREATE INDEX PRODUTO_COSIF_COD_CLASSIFICACAO_IDX ON PUBLIC.PRODUTO_COSIF USING BTREE(COD_CLASSIFICACAO);