spring:
    # Profile Configuration
    profiles:
        active: ${PROFILE}
    application:
        name: demo-application
    # DataSource Configuration
    datasource:
        driver-class-name: org.postgresql.Driver
        url: ${JDBC_DATABASE_URL}
        username: ${DATABASE_USERNAME}
        password: ${DATABASE_PASSWORD}
        sql-script-encoding: UTF-8
    # JACKSON properties
    jackson:
        property-naming-strategy: LOWER_CAMEL_CASE
    # JPA properties
    jpa:
        hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            jdbc:
                lob:
                    non_contextual_creation: true
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        open-in-view: false
    logging:
        pattern:
            console: "%d %-5level %logger : %msg%n"
        level:
            org.springframework: info
            org.hibernate: debug

# Server Configuration
server:
    port: ${SERVER_PORT} #set your port
    servlet:
        context-path: "/movement"